apiVersion: v2
name: ab-testing
description: A Helm chart for A/B Testing deployment strategy demonstration
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - deployment
  - ab-testing
  - release-strategy
maintainers:
  - name: K8s Deployment Showcase
