{{- if .Values.shadow.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shadow-mirroring.fullname" . }}-shadow
  labels:
    {{- include "shadow-mirroring.labels" . | nindent 4 }}
    version: shadow
spec:
  replicas: {{ .Values.shadow.replicaCount }}
  selector:
    matchLabels:
      {{- include "shadow-mirroring.selectorLabels" . | nindent 6 }}
      version: shadow
  template:
    metadata:
      labels:
        {{- include "shadow-mirroring.selectorLabels" . | nindent 8 }}
        version: shadow
    spec:
      containers:
        - name: app
          image: "{{ .Values.shadow.image.repository }}:{{ .Values.shadow.image.tag }}"
          imagePullPolicy: {{ .Values.shadow.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: APP_VERSION
              value: {{ .Values.shadow.version | quote }}
            - name: APP_COLOR
              value: "gray"
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: html-config
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-config
          configMap:
            name: {{ include "shadow-mirroring.fullname" . }}-shadow-html
{{- end }}
