{{- if .Values.stable.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "canary.fullname" . }}-stable
  labels:
    {{- include "canary.labels" . | nindent 4 }}
    version: stable
spec:
  replicas: {{ .Values.stable.replicaCount }}
  selector:
    matchLabels:
      {{- include "canary.selectorLabels" . | nindent 6 }}
      version: stable
  template:
    metadata:
      labels:
        {{- include "canary.selectorLabels" . | nindent 8 }}
        version: stable
    spec:
      containers:
        - name: app
          image: "{{ .Values.stable.image.repository }}:{{ .Values.stable.image.tag }}"
          imagePullPolicy: {{ .Values.stable.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: APP_VERSION
              value: {{ .Values.stable.version | quote }}
            - name: APP_COLOR
              value: "blue"
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: html-config
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-config
          configMap:
            name: {{ include "canary.fullname" . }}-stable-html
{{- end }}
